on: [repository_dispatch]

jobs:
  rebuild_qualtrics_data:
    runs-on: ubuntu-latest
    name: A job to rebuild the survey results from qualtrics
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./githubAction # Uses an action in the root directory
        id: hello
        with:
          repo: "Regrets_survey"
          owner: "outthinkgroup"
          github_access_token: ${{ secrets.ACCESS_TOKEN }}
          ip_stack_key: ${{ secrets.IP_STACK_TOKEN }}
          qualtrics_token: ${{ secrets.QUALTRICS_TOKEN }}
          survey_id: ${{ secrets.SURVEY_ID }}
          branch: staging
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
